on: pull_request

jobs:
  mr-checks:
    name: Merge Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Format
        run: pnpm run fmt:check

      - name: Run Lint
        run: pnpm run lint

      - name: Run Typecheck
        run: pnpm run typecheck

      - name: Run build
        run: pnpm run build
